enum Actions {
  LOAD_TWEETS = 'TWEETS::LOAD_TWEETS',
  PROMISE_LOAD_TWEETS = 'TWEETS::PROMISE_LOAD_TWEETS',
  RESOLVE_LOAD_TWEETS = 'TWEETS::RESOLVE_LOAD_TWEETS',
  REJECT_LOAD_TWEETS = 'TWEETS::REJECT_LOAD_TWEETS',
}

export default Actions;
